### PR TITLE
Scholarship section added

### PR DESCRIPTION
**Pull request by Sayak-0512**
I have added the scholarship section to the page as a carousel. Please review my work and give me your feedback. Thank you! :)

### CODE REVIEW

**Comment by chehak123** [comment]
Kindly add screenshots

**Comment by chehak123** [comment]
and pull the recent changes

**Comment by Sayak-0512** [comment]
Okay I am pulling the recent changes and adding the screenshots here.

**Comment by Sayak-0512** [comment]
Screenshot from 2021-01-25 00-02-30
Screenshot from 2021-01-25 00-02-38
Screenshot from 2021-01-25 00-02-40
Screenshot from 2021-01-25 00-02-44

**Comment by Sayak-0512** [comment]
Here are the screenshots of the changes I have made. Waiting for your review! :)

**Comment by chehak123** [comment]
Resolve merge conflicts and add card carousel like it's there in testimonials or just a three card section and a read more link at bottom redirecting to scholarship page

**Comment by chehak123** [comment]
We would be adding carousel in hero section on homepage so it would look almost similar

**Comment by chehak123** [comment]
Are you working?

**Comment by Sayak-0512** [comment]
Yes I am working on it! I will be sending you the screenshots by today!

**Comment by chehak123** [comment]
Have you completed?

**Comment by Sayak-0512** [comment]
Screenshot from 2021-01-27 13-19-28

I had some issues with my laptop. So, I couldn't work yesterday. Sorry for the delay. Here is the screenshot of the changes I have made! Kindly review my work and send me feedback! Thank you! :)

**Comment by chehak123** [comment]
Pm me on discord by today

**Pull request closed without merging**
