### PR TITLE
modified

### PR DESCRIPTION
**Pull request by Malvika18**
solved issue #3

### CODE REVIEW

**Comment by ineffable23** [comment]
@Malvika18 please add screenshot of the work you've done.

**Comment by Malvika18** [comment]
Screenshot (23)

**Comment by Malvika18** [comment]
Screenshot (24)

**Comment by chehak123** [comment]
Good job @Malvika18. Please do the following changes in your code
1. Divide footer in three part. In first one add any logo for now and 1-2 line about us info. In second part add all the navlinks in vertical order and in the third one add newsletter section.
2. Navbar is perfect. Just add a favicon with login button.
3. Remove the about us section.  Add carousel instead or design an innovative hero section.

**Comment by Malvika18** [comment]
@chehak123 ,please review the changes .

**Comment by chehak123** [comment]
Kindly add screenshots

**Comment by Malvika18** [comment]
Screenshot (29)

**Comment by chehak123** [comment]
@Malvika18 pull the existing changes and add proper screenshots. Footer screenshot is missing and navbar too.

**Comment by Malvika18** [comment]
Screenshot (30)

**Comment by Malvika18** [comment]
Screenshot (31)

**Pull request closed without merging**
